require 'knn/validations/leave_one_out'
require 'knn/validations/leave_one_out_multi'
require 'knn/validations/leave_three_out_multi'
require 'knn/validations/k_fold'
require 'knn/validations/k_fold_confusion_classification'
